[Fri Feb 14 06:43:49.388284 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035] mod_wsgi (pid=26679): Target WSGI script '/home/harryghgim/django_project/django_project/wsgi.py' cannot be loaded as Python module.
[Fri Feb 14 06:43:49.388369 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035] mod_wsgi (pid=26679): Exception occurred processing WSGI script '/home/harryghgim/django_project/django_project/wsgi.py'.
[Fri Feb 14 06:43:49.388622 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035] Traceback (most recent call last):
[Fri Feb 14 06:43:49.388720 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/home/harryghgim/django_project/django_project/wsgi.py", line 16, in <module>
[Fri Feb 14 06:43:49.388726 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     application = get_wsgi_application()
[Fri Feb 14 06:43:49.388734 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/home/harryghgim/django_project/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Feb 14 06:43:49.388739 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     django.setup(set_prefix=False)
[Fri Feb 14 06:43:49.388745 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/home/harryghgim/django_project/venv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
[Fri Feb 14 06:43:49.388750 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Feb 14 06:43:49.388757 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/home/harryghgim/django_project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
[Fri Feb 14 06:43:49.388760 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     self._setup(name)
[Fri Feb 14 06:43:49.388766 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/home/harryghgim/django_project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
[Fri Feb 14 06:43:49.388770 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     self._wrapped = Settings(settings_module)
[Fri Feb 14 06:43:49.388777 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/home/harryghgim/django_project/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
[Fri Feb 14 06:43:49.388781 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Feb 14 06:43:49.388787 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Fri Feb 14 06:43:49.388790 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Feb 14 06:43:49.388813 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Fri Feb 14 06:43:49.388820 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Fri Feb 14 06:43:49.388826 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
[Fri Feb 14 06:43:49.388832 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[Fri Feb 14 06:43:49.388837 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[Fri Feb 14 06:43:49.388843 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Fri Feb 14 06:43:49.388850 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/home/harryghgim/django_project/django_project/settings.py", line 17, in <module>
[Fri Feb 14 06:43:49.388853 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     config = json.load(config_file)
[Fri Feb 14 06:43:49.388859 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
[Fri Feb 14 06:43:49.388862 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
[Fri Feb 14 06:43:49.388867 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
[Fri Feb 14 06:43:49.388871 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     return _default_decoder.decode(s)
[Fri Feb 14 06:43:49.388876 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
[Fri Feb 14 06:43:49.388879 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Fri Feb 14 06:43:49.388886 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]   File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
[Fri Feb 14 06:43:49.388889 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035]     obj, end = self.scan_once(s, idx)
[Fri Feb 14 06:43:49.388909 2020] [wsgi:error] [pid 26679:tid 140324755478272] [remote 121.131.97.11:51035] json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 129)